//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIX2.Acquisition.IBM.Test {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.bigfix.com/Relevance", ConfigurationName="Test.RelevancePortType")]
    public interface RelevancePortType {
        
        // CODEGEN: Parameter 'a' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.bigfix.com/Relevance/soapaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="a")]
        MIX2.Acquisition.IBM.Test.GetRelevanceResultResponse GetRelevanceResult(MIX2.Acquisition.IBM.Test.GetRelevanceResultRequest request);
        
        // CODEGEN: Generating message contract since message GetStructuredRelevanceResultRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.bigfix.com/Relevance/soapaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MIX2.Acquisition.IBM.Test.GetStructuredRelevanceResultResponse GetStructuredRelevanceResult(MIX2.Acquisition.IBM.Test.GetStructuredRelevanceResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRelevanceResult", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class GetRelevanceResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        public string relevanceExpr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=2)]
        public string password;
        
        public GetRelevanceResultRequest() {
        }
        
        public GetRelevanceResultRequest(string relevanceExpr, string username, string password) {
            this.relevanceExpr = relevanceExpr;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRelevanceResultResponse", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class GetRelevanceResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("a")]
        public string[] a;
        
        public GetRelevanceResultResponse() {
        }
        
        public GetRelevanceResultResponse(string[] a) {
            this.a = a;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticateHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class RequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class DashboardVariableIdentifier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dashboardIDField;
        
        private string variableNameField;
        
        private long databaseIDField;
        
        private bool databaseIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dashboardID {
            get {
                return this.dashboardIDField;
            }
            set {
                this.dashboardIDField = value;
                this.RaisePropertyChanged("dashboardID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string variableName {
            get {
                return this.variableNameField;
            }
            set {
                this.variableNameField = value;
                this.RaisePropertyChanged("variableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long databaseID {
            get {
                return this.databaseIDField;
            }
            set {
                this.databaseIDField = value;
                this.RaisePropertyChanged("databaseID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool databaseIDSpecified {
            get {
                return this.databaseIDFieldSpecified;
            }
            set {
                this.databaseIDFieldSpecified = value;
                this.RaisePropertyChanged("databaseIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class UserAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string logonNameField;
        
        private string fullNameField;
        
        private string passwordField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string logonName {
            get {
                return this.logonNameField;
            }
            set {
                this.logonNameField = value;
                this.RaisePropertyChanged("logonName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("fullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("role");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class ResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
                this.RaisePropertyChanged("sessionToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class ResultList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(System.DateTime), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FloatingPoint", typeof(double), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Integer", typeof(string), DataType="integer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("String", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Tuple", typeof(ResultList), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        FloatingPoint,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Tuple,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class StructuredRelevanceResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultList resultsField;
        
        private bool pluralField;
        
        private bool pluralFieldSpecified;
        
        private string typeField;
        
        private string evaltimeField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultList results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("results");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool plural {
            get {
                return this.pluralField;
            }
            set {
                this.pluralField = value;
                this.RaisePropertyChanged("plural");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pluralSpecified {
            get {
                return this.pluralFieldSpecified;
            }
            set {
                this.pluralFieldSpecified = value;
                this.RaisePropertyChanged("pluralSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string evaltime {
            get {
                return this.evaltimeField;
            }
            set {
                this.evaltimeField = value;
                this.RaisePropertyChanged("evaltime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class LoginHeader : RequestHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class AuthenticateHeader : RequestHeader {
        
        private string usernameField;
        
        private string sessionTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
                this.RaisePropertyChanged("sessionToken");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStructuredRelevanceResult", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class GetStructuredRelevanceResultRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
        public MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        public string relevanceExpr;
        
        public GetStructuredRelevanceResultRequest() {
        }
        
        public GetStructuredRelevanceResultRequest(MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement, string relevanceExpr) {
            this.RequestHeaderElement = RequestHeaderElement;
            this.relevanceExpr = relevanceExpr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStructuredRelevanceResultResponse", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class GetStructuredRelevanceResultResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
        public MIX2.Acquisition.IBM.Test.ResponseHeader ResponseHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        public MIX2.Acquisition.IBM.Test.StructuredRelevanceResult StructuredRelevanceResult;
        
        public GetStructuredRelevanceResultResponse() {
        }
        
        public GetStructuredRelevanceResultResponse(MIX2.Acquisition.IBM.Test.ResponseHeader ResponseHeaderElement, MIX2.Acquisition.IBM.Test.StructuredRelevanceResult StructuredRelevanceResult) {
            this.ResponseHeaderElement = ResponseHeaderElement;
            this.StructuredRelevanceResult = StructuredRelevanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RelevancePortTypeChannel : MIX2.Acquisition.IBM.Test.RelevancePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RelevancePortTypeClient : System.ServiceModel.ClientBase<MIX2.Acquisition.IBM.Test.RelevancePortType>, MIX2.Acquisition.IBM.Test.RelevancePortType {
        
        public RelevancePortTypeClient() {
        }
        
        public RelevancePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RelevancePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RelevancePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RelevancePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MIX2.Acquisition.IBM.Test.GetRelevanceResultResponse MIX2.Acquisition.IBM.Test.RelevancePortType.GetRelevanceResult(MIX2.Acquisition.IBM.Test.GetRelevanceResultRequest request) {
            return base.Channel.GetRelevanceResult(request);
        }
        
        public string[] GetRelevanceResult(string relevanceExpr, string username, string password) {
            MIX2.Acquisition.IBM.Test.GetRelevanceResultRequest inValue = new MIX2.Acquisition.IBM.Test.GetRelevanceResultRequest();
            inValue.relevanceExpr = relevanceExpr;
            inValue.username = username;
            inValue.password = password;
            MIX2.Acquisition.IBM.Test.GetRelevanceResultResponse retVal = ((MIX2.Acquisition.IBM.Test.RelevancePortType)(this)).GetRelevanceResult(inValue);
            return retVal.a;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MIX2.Acquisition.IBM.Test.GetStructuredRelevanceResultResponse MIX2.Acquisition.IBM.Test.RelevancePortType.GetStructuredRelevanceResult(MIX2.Acquisition.IBM.Test.GetStructuredRelevanceResultRequest request) {
            return base.Channel.GetStructuredRelevanceResult(request);
        }
        
        public MIX2.Acquisition.IBM.Test.ResponseHeader GetStructuredRelevanceResult(MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement, string relevanceExpr, out MIX2.Acquisition.IBM.Test.StructuredRelevanceResult StructuredRelevanceResult) {
            MIX2.Acquisition.IBM.Test.GetStructuredRelevanceResultRequest inValue = new MIX2.Acquisition.IBM.Test.GetStructuredRelevanceResultRequest();
            inValue.RequestHeaderElement = RequestHeaderElement;
            inValue.relevanceExpr = relevanceExpr;
            MIX2.Acquisition.IBM.Test.GetStructuredRelevanceResultResponse retVal = ((MIX2.Acquisition.IBM.Test.RelevancePortType)(this)).GetStructuredRelevanceResult(inValue);
            StructuredRelevanceResult = retVal.StructuredRelevanceResult;
            return retVal.ResponseHeaderElement;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.bigfix.com/Relevance", ConfigurationName="Test.UserManagementPortType")]
    public interface UserManagementPortType {
        
        // CODEGEN: Generating message contract since message CreateUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.bigfix.com/Relevance/soapaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MIX2.Acquisition.IBM.Test.CreateUserResponse CreateUser(MIX2.Acquisition.IBM.Test.CreateUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUser", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
        public MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        public MIX2.Acquisition.IBM.Test.UserAccount user;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement, MIX2.Acquisition.IBM.Test.UserAccount user) {
            this.RequestHeaderElement = RequestHeaderElement;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserResponse", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
        public MIX2.Acquisition.IBM.Test.ResponseHeader ResponseHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        public bool success;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(MIX2.Acquisition.IBM.Test.ResponseHeader ResponseHeaderElement, bool success) {
            this.ResponseHeaderElement = ResponseHeaderElement;
            this.success = success;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserManagementPortTypeChannel : MIX2.Acquisition.IBM.Test.UserManagementPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementPortTypeClient : System.ServiceModel.ClientBase<MIX2.Acquisition.IBM.Test.UserManagementPortType>, MIX2.Acquisition.IBM.Test.UserManagementPortType {
        
        public UserManagementPortTypeClient() {
        }
        
        public UserManagementPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MIX2.Acquisition.IBM.Test.CreateUserResponse MIX2.Acquisition.IBM.Test.UserManagementPortType.CreateUser(MIX2.Acquisition.IBM.Test.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public MIX2.Acquisition.IBM.Test.ResponseHeader CreateUser(MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement, MIX2.Acquisition.IBM.Test.UserAccount user, out bool success) {
            MIX2.Acquisition.IBM.Test.CreateUserRequest inValue = new MIX2.Acquisition.IBM.Test.CreateUserRequest();
            inValue.RequestHeaderElement = RequestHeaderElement;
            inValue.user = user;
            MIX2.Acquisition.IBM.Test.CreateUserResponse retVal = ((MIX2.Acquisition.IBM.Test.UserManagementPortType)(this)).CreateUser(inValue);
            success = retVal.success;
            return retVal.ResponseHeaderElement;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.bigfix.com/Relevance", ConfigurationName="Test.DashboardVariablePortType")]
    public interface DashboardVariablePortType {
        
        // CODEGEN: Generating message contract since message DeleteSharedVariableRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.bigfix.com/Relevance/soapaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MIX2.Acquisition.IBM.Test.DeleteSharedVariableResponse DeleteSharedVariable(MIX2.Acquisition.IBM.Test.DeleteSharedVariableRequest request);
        
        // CODEGEN: Generating message contract since message StoreSharedVariableRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.bigfix.com/Relevance/soapaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MIX2.Acquisition.IBM.Test.StoreSharedVariableResponse StoreSharedVariable(MIX2.Acquisition.IBM.Test.StoreSharedVariableRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSharedVariable", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class DeleteSharedVariableRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
        public MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        public MIX2.Acquisition.IBM.Test.DashboardVariableIdentifier dashboardVariableIdentifier;
        
        public DeleteSharedVariableRequest() {
        }
        
        public DeleteSharedVariableRequest(MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement, MIX2.Acquisition.IBM.Test.DashboardVariableIdentifier dashboardVariableIdentifier) {
            this.RequestHeaderElement = RequestHeaderElement;
            this.dashboardVariableIdentifier = dashboardVariableIdentifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSharedVariableResponse", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class DeleteSharedVariableResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
        public MIX2.Acquisition.IBM.Test.ResponseHeader ResponseHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        public bool success;
        
        public DeleteSharedVariableResponse() {
        }
        
        public DeleteSharedVariableResponse(MIX2.Acquisition.IBM.Test.ResponseHeader ResponseHeaderElement, bool success) {
            this.ResponseHeaderElement = ResponseHeaderElement;
            this.success = success;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StoreSharedVariable", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class StoreSharedVariableRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
        public MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        public MIX2.Acquisition.IBM.Test.DashboardVariableIdentifier dashboardVariableIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=1)]
        public string variableValue;
        
        public StoreSharedVariableRequest() {
        }
        
        public StoreSharedVariableRequest(MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement, MIX2.Acquisition.IBM.Test.DashboardVariableIdentifier dashboardVariableIdentifier, string variableValue) {
            this.RequestHeaderElement = RequestHeaderElement;
            this.dashboardVariableIdentifier = dashboardVariableIdentifier;
            this.variableValue = variableValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StoreSharedVariableResponse", WrapperNamespace="http://schemas.bigfix.com/Relevance", IsWrapped=true)]
    public partial class StoreSharedVariableResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
        public MIX2.Acquisition.IBM.Test.ResponseHeader ResponseHeaderElement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.bigfix.com/Relevance", Order=0)]
        public bool success;
        
        public StoreSharedVariableResponse() {
        }
        
        public StoreSharedVariableResponse(MIX2.Acquisition.IBM.Test.ResponseHeader ResponseHeaderElement, bool success) {
            this.ResponseHeaderElement = ResponseHeaderElement;
            this.success = success;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DashboardVariablePortTypeChannel : MIX2.Acquisition.IBM.Test.DashboardVariablePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DashboardVariablePortTypeClient : System.ServiceModel.ClientBase<MIX2.Acquisition.IBM.Test.DashboardVariablePortType>, MIX2.Acquisition.IBM.Test.DashboardVariablePortType {
        
        public DashboardVariablePortTypeClient() {
        }
        
        public DashboardVariablePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DashboardVariablePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardVariablePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardVariablePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MIX2.Acquisition.IBM.Test.DeleteSharedVariableResponse MIX2.Acquisition.IBM.Test.DashboardVariablePortType.DeleteSharedVariable(MIX2.Acquisition.IBM.Test.DeleteSharedVariableRequest request) {
            return base.Channel.DeleteSharedVariable(request);
        }
        
        public MIX2.Acquisition.IBM.Test.ResponseHeader DeleteSharedVariable(MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement, MIX2.Acquisition.IBM.Test.DashboardVariableIdentifier dashboardVariableIdentifier, out bool success) {
            MIX2.Acquisition.IBM.Test.DeleteSharedVariableRequest inValue = new MIX2.Acquisition.IBM.Test.DeleteSharedVariableRequest();
            inValue.RequestHeaderElement = RequestHeaderElement;
            inValue.dashboardVariableIdentifier = dashboardVariableIdentifier;
            MIX2.Acquisition.IBM.Test.DeleteSharedVariableResponse retVal = ((MIX2.Acquisition.IBM.Test.DashboardVariablePortType)(this)).DeleteSharedVariable(inValue);
            success = retVal.success;
            return retVal.ResponseHeaderElement;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MIX2.Acquisition.IBM.Test.StoreSharedVariableResponse MIX2.Acquisition.IBM.Test.DashboardVariablePortType.StoreSharedVariable(MIX2.Acquisition.IBM.Test.StoreSharedVariableRequest request) {
            return base.Channel.StoreSharedVariable(request);
        }
        
        public MIX2.Acquisition.IBM.Test.ResponseHeader StoreSharedVariable(MIX2.Acquisition.IBM.Test.RequestHeader RequestHeaderElement, MIX2.Acquisition.IBM.Test.DashboardVariableIdentifier dashboardVariableIdentifier, string variableValue, out bool success) {
            MIX2.Acquisition.IBM.Test.StoreSharedVariableRequest inValue = new MIX2.Acquisition.IBM.Test.StoreSharedVariableRequest();
            inValue.RequestHeaderElement = RequestHeaderElement;
            inValue.dashboardVariableIdentifier = dashboardVariableIdentifier;
            inValue.variableValue = variableValue;
            MIX2.Acquisition.IBM.Test.StoreSharedVariableResponse retVal = ((MIX2.Acquisition.IBM.Test.DashboardVariablePortType)(this)).StoreSharedVariable(inValue);
            success = retVal.success;
            return retVal.ResponseHeaderElement;
        }
    }
}
