//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIn.Ventures.BaseLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AInVentureEntities : DbContext
    {
        public AInVentureEntities()
            : base("name=AInVentureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<AlertType> AlertTypes { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<ComponentToComponent> ComponentToComponents { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<RoleToProject> RoleToProjects { get; set; }
        public virtual DbSet<Stakeholder> Stakeholders { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<StakeholderType> StakeholderTypes { get; set; }
        public virtual DbSet<Archived_Project> Archived_Project { get; set; }
        public virtual DbSet<Archived_RoleToProject> Archived_RoleToProject { get; set; }
        public virtual DbSet<Archived_Stakeholder> Archived_Stakeholder { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<Colleague> Colleagues { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<DataClass> DataClasses { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<QPoint> QPoints { get; set; }
        public virtual DbSet<QPointToCategory> QPointToCategories { get; set; }
        public virtual DbSet<QPointToProperty> QPointToProperties { get; set; }
        public virtual DbSet<QPointToSource> QPointToSources { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
    
        [DbFunction("AInVentureEntities", "getModule")]
        public virtual IQueryable<getModule_Result> getModule(Nullable<System.Guid> oBJECTGUID)
        {
            var oBJECTGUIDParameter = oBJECTGUID.HasValue ?
                new ObjectParameter("OBJECTGUID", oBJECTGUID) :
                new ObjectParameter("OBJECTGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getModule_Result>("[AInVentureEntities].[getModule](@OBJECTGUID)", oBJECTGUIDParameter);
        }
    
        public virtual int CreateAlert(string type, string text, string typeID)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            var typeIDParameter = typeID != null ?
                new ObjectParameter("TypeID", typeID) :
                new ObjectParameter("TypeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateAlert", typeParameter, textParameter, typeIDParameter);
        }
    
        public virtual int CreateAlertType(string typeID, string name, string description)
        {
            var typeIDParameter = typeID != null ?
                new ObjectParameter("TypeID", typeID) :
                new ObjectParameter("TypeID", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateAlertType", typeIDParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int CreateCollaborator(Nullable<System.Guid> collaboratorGUID, Nullable<System.Guid> colleagueGUID, string role, Nullable<System.Guid> gUID, Nullable<System.Guid> projectGUID)
        {
            var collaboratorGUIDParameter = collaboratorGUID.HasValue ?
                new ObjectParameter("CollaboratorGUID", collaboratorGUID) :
                new ObjectParameter("CollaboratorGUID", typeof(System.Guid));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateCollaborator", collaboratorGUIDParameter, colleagueGUIDParameter, roleParameter, gUIDParameter, projectGUIDParameter);
        }
    
        public virtual int CreateColleague(Nullable<System.Guid> colleagueGUID, string givenName, string surName, string phoneNumber, string emailAddress)
        {
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            var givenNameParameter = givenName != null ?
                new ObjectParameter("GivenName", givenName) :
                new ObjectParameter("GivenName", typeof(string));
    
            var surNameParameter = surName != null ?
                new ObjectParameter("SurName", surName) :
                new ObjectParameter("SurName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateColleague", colleagueGUIDParameter, givenNameParameter, surNameParameter, phoneNumberParameter, emailAddressParameter);
        }
    
        public virtual int CreateComponent(Nullable<System.Guid> objectGUID, string componentType, string name, string description, Nullable<System.Guid> projectGUID, Nullable<System.Guid> parentGUID, Nullable<int> amountInParent)
        {
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            var componentTypeParameter = componentType != null ?
                new ObjectParameter("ComponentType", componentType) :
                new ObjectParameter("ComponentType", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            var parentGUIDParameter = parentGUID.HasValue ?
                new ObjectParameter("ParentGUID", parentGUID) :
                new ObjectParameter("ParentGUID", typeof(System.Guid));
    
            var amountInParentParameter = amountInParent.HasValue ?
                new ObjectParameter("AmountInParent", amountInParent) :
                new ObjectParameter("AmountInParent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateComponent", objectGUIDParameter, componentTypeParameter, nameParameter, descriptionParameter, projectGUIDParameter, parentGUIDParameter, amountInParentParameter);
        }
    
        public virtual int CreateComponentToComponent(Nullable<System.Guid> parentGUID, Nullable<System.Guid> objectGUID, Nullable<int> amount)
        {
            var parentGUIDParameter = parentGUID.HasValue ?
                new ObjectParameter("ParentGUID", parentGUID) :
                new ObjectParameter("ParentGUID", typeof(System.Guid));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateComponentToComponent", parentGUIDParameter, objectGUIDParameter, amountParameter);
        }
    
        public virtual int CreateProductCode(string type, string value)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateProductCode", typeParameter, valueParameter);
        }
    
        public virtual int CreateProject(Nullable<System.Guid> projectGUID, string projectName, string description, Nullable<double> shares, Nullable<System.Guid> creatorGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            var projectNameParameter = projectName != null ?
                new ObjectParameter("ProjectName", projectName) :
                new ObjectParameter("ProjectName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var sharesParameter = shares.HasValue ?
                new ObjectParameter("Shares", shares) :
                new ObjectParameter("Shares", typeof(double));
    
            var creatorGUIDParameter = creatorGUID.HasValue ?
                new ObjectParameter("CreatorGUID", creatorGUID) :
                new ObjectParameter("CreatorGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateProject", projectGUIDParameter, projectNameParameter, descriptionParameter, sharesParameter, creatorGUIDParameter);
        }
    
        public virtual int CreateProjectToProduct(Nullable<System.Guid> projectGUID, Nullable<System.Guid> objectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateProjectToProduct", projectGUIDParameter, objectGUIDParameter);
        }
    
        public virtual int CreateRole(string name, string description)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateRole", nameParameter, descriptionParameter);
        }
    
        public virtual int CreateStakeholder(Nullable<System.Guid> gUID, byte[] type, Nullable<double> shares, Nullable<System.Guid> projectGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(byte[]));
    
            var sharesParameter = shares.HasValue ?
                new ObjectParameter("Shares", shares) :
                new ObjectParameter("Shares", typeof(double));
    
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateStakeholder", gUIDParameter, typeParameter, sharesParameter, projectGUIDParameter);
        }
    
        public virtual int CreateStakeholderType(string typeID, string name, string description)
        {
            var typeIDParameter = typeID != null ?
                new ObjectParameter("TypeID", typeID) :
                new ObjectParameter("TypeID", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateStakeholderType", typeIDParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int CreateUser(Nullable<System.Guid> gUID, string emailAddress, string givenNames, string surname, string pwd)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var givenNamesParameter = givenNames != null ?
                new ObjectParameter("GivenNames", givenNames) :
                new ObjectParameter("GivenNames", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("Pwd", pwd) :
                new ObjectParameter("Pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateUser", gUIDParameter, emailAddressParameter, givenNamesParameter, surnameParameter, pwdParameter);
        }
    
        public virtual int DeleteAlerts_ByType(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAlerts_ByType", param1Parameter);
        }
    
        public virtual int DeleteAlerts_ByTypeID(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAlerts_ByTypeID", param1Parameter);
        }
    
        public virtual int DeleteAlertTypes_ByName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAlertTypes_ByName", param1Parameter);
        }
    
        public virtual int DeleteAlertTypes_ByTypeID(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAlertTypes_ByTypeID", param1Parameter);
        }
    
        public virtual int DeleteCollaborators_ByCollaboratorGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCollaborators_ByCollaboratorGUID", param1Parameter);
        }
    
        public virtual int DeleteCollaborators_ByColleagueGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCollaborators_ByColleagueGUID", param1Parameter);
        }
    
        public virtual int DeleteCollaborators_ByGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCollaborators_ByGUID", param1Parameter);
        }
    
        public virtual int DeleteCollaborators_ByRole(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCollaborators_ByRole", param1Parameter);
        }
    
        public virtual int DeleteColleaguePhoneNumberTypes_ByName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleaguePhoneNumberTypes_ByName", param1Parameter);
        }
    
        public virtual int DeleteColleaguePhoneNumberTypes_ByTypeID(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleaguePhoneNumberTypes_ByTypeID", param1Parameter);
        }
    
        public virtual int DeleteColleagues_ByColleagueGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleagues_ByColleagueGUID", param1Parameter);
        }
    
        public virtual int DeleteColleagues_ByEmailAddress(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleagues_ByEmailAddress", param1Parameter);
        }
    
        public virtual int DeleteColleagues_ByEmailAddress_Domain(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleagues_ByEmailAddress_Domain", param1Parameter);
        }
    
        public virtual int DeleteColleagues_ByEmailAddress_Name(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleagues_ByEmailAddress_Name", param1Parameter);
        }
    
        public virtual int DeleteColleagues_ByGivenName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleagues_ByGivenName", param1Parameter);
        }
    
        public virtual int DeleteColleagues_ByPhoneNumber(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleagues_ByPhoneNumber", param1Parameter);
        }
    
        public virtual int DeleteColleagues_ByPhoneNumber_CountryCode(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleagues_ByPhoneNumber_CountryCode", param1Parameter);
        }
    
        public virtual int DeleteColleagues_BySurName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleagues_BySurName", param1Parameter);
        }
    
        public virtual int DeleteProductCodes_ByType(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProductCodes_ByType", typeParameter);
        }
    
        public virtual int DeleteProductCodes_ByValue(string value)
        {
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProductCodes_ByValue", valueParameter);
        }
    
        public virtual int DeleteProducts_ByProjectGUID(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProducts_ByProjectGUID", projectGUIDParameter);
        }
    
        public virtual int DeleteProjects_ByProjectGUID(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProjects_ByProjectGUID", projectGUIDParameter);
        }
    
        public virtual int DeleteProjectToProduct(Nullable<System.Guid> projectGUID, Nullable<System.Guid> objectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProjectToProduct", projectGUIDParameter, objectGUIDParameter);
        }
    
        public virtual int DeleteProjectToProduct_ByObjectGUID(Nullable<System.Guid> objectGUID)
        {
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProjectToProduct_ByObjectGUID", objectGUIDParameter);
        }
    
        public virtual int DeleteProjectToProduct_ByProjectGUID(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProjectToProduct_ByProjectGUID", projectGUIDParameter);
        }
    
        public virtual int DeleteRoles_ByName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteRoles_ByName", param1Parameter);
        }
    
        public virtual int DeleteStakeholders_ByGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStakeholders_ByGUID", param1Parameter);
        }
    
        public virtual int DeleteStakeholders_ByType(byte[] param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStakeholders_ByType", param1Parameter);
        }
    
        public virtual int DeleteStakeholderTypes_ByName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStakeholderTypes_ByName", param1Parameter);
        }
    
        public virtual int DeleteStakeholderTypes_ByTypeID(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStakeholderTypes_ByTypeID", param1Parameter);
        }
    
        public virtual ObjectResult<GetAlerts_ByType_Result> GetAlerts_ByType(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAlerts_ByType_Result>("GetAlerts_ByType", param1Parameter);
        }
    
        public virtual ObjectResult<GetAlerts_ByTypeID_Result> GetAlerts_ByTypeID(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAlerts_ByTypeID_Result>("GetAlerts_ByTypeID", param1Parameter);
        }
    
        public virtual ObjectResult<GetAlertTypes_ByName_Result> GetAlertTypes_ByName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAlertTypes_ByName_Result>("GetAlertTypes_ByName", param1Parameter);
        }
    
        public virtual ObjectResult<GetAlertTypes_ByTypeID_Result> GetAlertTypes_ByTypeID(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAlertTypes_ByTypeID_Result>("GetAlertTypes_ByTypeID", param1Parameter);
        }
    
        public virtual ObjectResult<GetCollaborators_ByCollaboratorGUID_Result> GetCollaborators_ByCollaboratorGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCollaborators_ByCollaboratorGUID_Result>("GetCollaborators_ByCollaboratorGUID", param1Parameter);
        }
    
        public virtual ObjectResult<GetCollaborators_ByColleagueGUID_Result> GetCollaborators_ByColleagueGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCollaborators_ByColleagueGUID_Result>("GetCollaborators_ByColleagueGUID", param1Parameter);
        }
    
        public virtual ObjectResult<GetCollaborators_ByGUID_Result> GetCollaborators_ByGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCollaborators_ByGUID_Result>("GetCollaborators_ByGUID", param1Parameter);
        }
    
        public virtual ObjectResult<GetCollaborators_ByProjectGUID_Result> GetCollaborators_ByProjectGUID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCollaborators_ByProjectGUID_Result>("GetCollaborators_ByProjectGUID");
        }
    
        public virtual ObjectResult<GetCollaborators_ByRole_Result> GetCollaborators_ByRole(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCollaborators_ByRole_Result>("GetCollaborators_ByRole", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleaguePhoneNumberTypes_ByName_Result> GetColleaguePhoneNumberTypes_ByName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleaguePhoneNumberTypes_ByName_Result>("GetColleaguePhoneNumberTypes_ByName", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleaguePhoneNumberTypes_ByTypeID_Result> GetColleaguePhoneNumberTypes_ByTypeID(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleaguePhoneNumberTypes_ByTypeID_Result>("GetColleaguePhoneNumberTypes_ByTypeID", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleagues_ByColleagueGUID_Result> GetColleagues_ByColleagueGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleagues_ByColleagueGUID_Result>("GetColleagues_ByColleagueGUID", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleagues_ByEmailAddress_Result> GetColleagues_ByEmailAddress(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleagues_ByEmailAddress_Result>("GetColleagues_ByEmailAddress", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleagues_ByEmailAddress_Domain_Result> GetColleagues_ByEmailAddress_Domain(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleagues_ByEmailAddress_Domain_Result>("GetColleagues_ByEmailAddress_Domain", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleagues_ByEmailAddress_Name_Result> GetColleagues_ByEmailAddress_Name(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleagues_ByEmailAddress_Name_Result>("GetColleagues_ByEmailAddress_Name", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleagues_ByGivenName_Result> GetColleagues_ByGivenName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleagues_ByGivenName_Result>("GetColleagues_ByGivenName", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleagues_ByPhoneNumber_Result> GetColleagues_ByPhoneNumber(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleagues_ByPhoneNumber_Result>("GetColleagues_ByPhoneNumber", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleagues_ByPhoneNumber_CountryCode_Result> GetColleagues_ByPhoneNumber_CountryCode(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleagues_ByPhoneNumber_CountryCode_Result>("GetColleagues_ByPhoneNumber_CountryCode", param1Parameter);
        }
    
        public virtual ObjectResult<GetColleagues_BySurName_Result> GetColleagues_BySurName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleagues_BySurName_Result>("GetColleagues_BySurName", param1Parameter);
        }
    
        public virtual ObjectResult<GetComponents_ByParentGUID_Result> GetComponents_ByParentGUID(Nullable<System.Guid> parentGUID)
        {
            var parentGUIDParameter = parentGUID.HasValue ?
                new ObjectParameter("ParentGUID", parentGUID) :
                new ObjectParameter("ParentGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetComponents_ByParentGUID_Result>("GetComponents_ByParentGUID", parentGUIDParameter);
        }
    
        public virtual ObjectResult<GetProductCodes_ByType_Result> GetProductCodes_ByType(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductCodes_ByType_Result>("GetProductCodes_ByType", typeParameter);
        }
    
        public virtual ObjectResult<GetProductCodes_ByValue_Result> GetProductCodes_ByValue(string value)
        {
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductCodes_ByValue_Result>("GetProductCodes_ByValue", valueParameter);
        }
    
        public virtual int GetProducts_ByProjectGUID(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetProducts_ByProjectGUID", projectGUIDParameter);
        }
    
        public virtual ObjectResult<GetProducts_ByProjectGUID1_Result> GetProducts_ByProjectGUID1(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProducts_ByProjectGUID1_Result>("GetProducts_ByProjectGUID1", projectGUIDParameter);
        }
    
        public virtual ObjectResult<GetProjects_Result> GetProjects()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjects_Result>("GetProjects");
        }
    
        public virtual ObjectResult<GetProjects_ByProjectGUID_Result> GetProjects_ByProjectGUID(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjects_ByProjectGUID_Result>("GetProjects_ByProjectGUID", projectGUIDParameter);
        }
    
        public virtual ObjectResult<GetProjectToProduct_ByObjectGUID_Result> GetProjectToProduct_ByObjectGUID(Nullable<System.Guid> objectGUID)
        {
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectToProduct_ByObjectGUID_Result>("GetProjectToProduct_ByObjectGUID", objectGUIDParameter);
        }
    
        public virtual ObjectResult<GetProjectToProduct_ByProjectGUID_Result> GetProjectToProduct_ByProjectGUID(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectToProduct_ByProjectGUID_Result>("GetProjectToProduct_ByProjectGUID", projectGUIDParameter);
        }
    
        public virtual ObjectResult<GetRoles_ByName_Result> GetRoles_ByName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRoles_ByName_Result>("GetRoles_ByName", param1Parameter);
        }
    
        public virtual ObjectResult<GetStakeholders_ByGUID_Result> GetStakeholders_ByGUID(Nullable<System.Guid> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStakeholders_ByGUID_Result>("GetStakeholders_ByGUID", param1Parameter);
        }
    
        public virtual ObjectResult<GetStakeholders_ByProjectGUID_Result> GetStakeholders_ByProjectGUID(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStakeholders_ByProjectGUID_Result>("GetStakeholders_ByProjectGUID", projectGUIDParameter);
        }
    
        public virtual ObjectResult<GetStakeholders_ByType_Result> GetStakeholders_ByType(byte[] param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStakeholders_ByType_Result>("GetStakeholders_ByType", param1Parameter);
        }
    
        public virtual ObjectResult<GetStakeholderTypes_ByName_Result> GetStakeholderTypes_ByName(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStakeholderTypes_ByName_Result>("GetStakeholderTypes_ByName", param1Parameter);
        }
    
        public virtual ObjectResult<GetStakeholderTypes_ByTypeID_Result> GetStakeholderTypes_ByTypeID(string param1)
        {
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStakeholderTypes_ByTypeID_Result>("GetStakeholderTypes_ByTypeID", param1Parameter);
        }
    
        public virtual ObjectResult<GetUser_ByEmail_Result> GetUser_ByEmail(string emailAddress)
        {
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUser_ByEmail_Result>("GetUser_ByEmail", emailAddressParameter);
        }
    
        public virtual int InsertComponent(Nullable<System.Guid> objectGUID, string componentType, string name, string description, Nullable<decimal> price, string manufacturer, string sKU, string supplier)
        {
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            var componentTypeParameter = componentType != null ?
                new ObjectParameter("ComponentType", componentType) :
                new ObjectParameter("ComponentType", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var manufacturerParameter = manufacturer != null ?
                new ObjectParameter("Manufacturer", manufacturer) :
                new ObjectParameter("Manufacturer", typeof(string));
    
            var sKUParameter = sKU != null ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(string));
    
            var supplierParameter = supplier != null ?
                new ObjectParameter("Supplier", supplier) :
                new ObjectParameter("Supplier", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertComponent", objectGUIDParameter, componentTypeParameter, nameParameter, descriptionParameter, priceParameter, manufacturerParameter, sKUParameter, supplierParameter);
        }
    
        public virtual int InsertComponentToComponent(Nullable<System.Guid> parentGUID, Nullable<System.Guid> objectGUID, Nullable<int> amount)
        {
            var parentGUIDParameter = parentGUID.HasValue ?
                new ObjectParameter("ParentGUID", parentGUID) :
                new ObjectParameter("ParentGUID", typeof(System.Guid));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertComponentToComponent", parentGUIDParameter, objectGUIDParameter, amountParameter);
        }
    
        public virtual int UpdateAlert_Text_ByText(string textNew, string textOld)
        {
            var textNewParameter = textNew != null ?
                new ObjectParameter("TextNew", textNew) :
                new ObjectParameter("TextNew", typeof(string));
    
            var textOldParameter = textOld != null ?
                new ObjectParameter("TextOld", textOld) :
                new ObjectParameter("TextOld", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAlert_Text_ByText", textNewParameter, textOldParameter);
        }
    
        public virtual int UpdateAlertType_Description_ByName(string description, string name)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAlertType_Description_ByName", descriptionParameter, nameParameter);
        }
    
        public virtual int UpdateAlertType_Description_ByTypeID(string description, string typeID)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var typeIDParameter = typeID != null ?
                new ObjectParameter("TypeID", typeID) :
                new ObjectParameter("TypeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAlertType_Description_ByTypeID", descriptionParameter, typeIDParameter);
        }
    
        public virtual int UpdateCollaborator_Role_ByCollaboratorGUID(string role, Nullable<System.Guid> collaboratorGUID)
        {
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            var collaboratorGUIDParameter = collaboratorGUID.HasValue ?
                new ObjectParameter("CollaboratorGUID", collaboratorGUID) :
                new ObjectParameter("CollaboratorGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCollaborator_Role_ByCollaboratorGUID", roleParameter, collaboratorGUIDParameter);
        }
    
        public virtual int UpdateColleague_ByColleagueGUID(string givenName, string surName, string phoneNumber, string emailAddress, Nullable<System.Guid> colleagueGUID)
        {
            var givenNameParameter = givenName != null ?
                new ObjectParameter("GivenName", givenName) :
                new ObjectParameter("GivenName", typeof(string));
    
            var surNameParameter = surName != null ?
                new ObjectParameter("SurName", surName) :
                new ObjectParameter("SurName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateColleague_ByColleagueGUID", givenNameParameter, surNameParameter, phoneNumberParameter, emailAddressParameter, colleagueGUIDParameter);
        }
    
        public virtual int UpdateColleague_EmailAddress_ByColleagueGUID(string emailAddress, Nullable<System.Guid> colleagueGUID)
        {
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateColleague_EmailAddress_ByColleagueGUID", emailAddressParameter, colleagueGUIDParameter);
        }
    
        public virtual int UpdateColleague_GivenName_ByColleagueGUID(string givenName, Nullable<System.Guid> colleagueGUID)
        {
            var givenNameParameter = givenName != null ?
                new ObjectParameter("GivenName", givenName) :
                new ObjectParameter("GivenName", typeof(string));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateColleague_GivenName_ByColleagueGUID", givenNameParameter, colleagueGUIDParameter);
        }
    
        public virtual int UpdateColleague_PhoneNumber_ByColleagueGUID(string phoneNumber, Nullable<System.Guid> colleagueGUID)
        {
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateColleague_PhoneNumber_ByColleagueGUID", phoneNumberParameter, colleagueGUIDParameter);
        }
    
        public virtual int UpdateColleague_SurName_ByColleagueGUID(string surName, Nullable<System.Guid> colleagueGUID)
        {
            var surNameParameter = surName != null ?
                new ObjectParameter("SurName", surName) :
                new ObjectParameter("SurName", typeof(string));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateColleague_SurName_ByColleagueGUID", surNameParameter, colleagueGUIDParameter);
        }
    
        public virtual int UpdateColleaguePhoneNumberType_ByTypeID(string name, string typeID)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var typeIDParameter = typeID != null ?
                new ObjectParameter("TypeID", typeID) :
                new ObjectParameter("TypeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateColleaguePhoneNumberType_ByTypeID", nameParameter, typeIDParameter);
        }
    
        public virtual int UpdateComponent_ByObjectGUID(Nullable<System.Guid> objectGUID, string componentType, string name, string description, Nullable<decimal> price, string manufacturer, string sKU, string supplier, Nullable<System.Guid> projectGUID)
        {
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            var componentTypeParameter = componentType != null ?
                new ObjectParameter("ComponentType", componentType) :
                new ObjectParameter("ComponentType", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var manufacturerParameter = manufacturer != null ?
                new ObjectParameter("Manufacturer", manufacturer) :
                new ObjectParameter("Manufacturer", typeof(string));
    
            var sKUParameter = sKU != null ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(string));
    
            var supplierParameter = supplier != null ?
                new ObjectParameter("Supplier", supplier) :
                new ObjectParameter("Supplier", typeof(string));
    
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComponent_ByObjectGUID", objectGUIDParameter, componentTypeParameter, nameParameter, descriptionParameter, priceParameter, manufacturerParameter, sKUParameter, supplierParameter, projectGUIDParameter);
        }
    
        public virtual int UpdateComponent_ComponentType_ByObjectGUID(string componentType, Nullable<System.Guid> objectGUID)
        {
            var componentTypeParameter = componentType != null ?
                new ObjectParameter("ComponentType", componentType) :
                new ObjectParameter("ComponentType", typeof(string));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComponent_ComponentType_ByObjectGUID", componentTypeParameter, objectGUIDParameter);
        }
    
        public virtual int UpdateComponent_Description_ByObjectGUID(string description, Nullable<System.Guid> objectGUID)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComponent_Description_ByObjectGUID", descriptionParameter, objectGUIDParameter);
        }
    
        public virtual int UpdateComponent_Manufacturer_ByObjectGUID(string manufacturer, Nullable<System.Guid> objectGUID)
        {
            var manufacturerParameter = manufacturer != null ?
                new ObjectParameter("Manufacturer", manufacturer) :
                new ObjectParameter("Manufacturer", typeof(string));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComponent_Manufacturer_ByObjectGUID", manufacturerParameter, objectGUIDParameter);
        }
    
        public virtual int UpdateComponent_Name_ByObjectGUID(string name, Nullable<System.Guid> objectGUID)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComponent_Name_ByObjectGUID", nameParameter, objectGUIDParameter);
        }
    
        public virtual int UpdateComponent_Price_ByObjectGUID(Nullable<decimal> price, Nullable<System.Guid> objectGUID)
        {
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComponent_Price_ByObjectGUID", priceParameter, objectGUIDParameter);
        }
    
        public virtual int UpdateComponent_ProjectGUID_ByObjectGUID(Nullable<System.Guid> projectGUID, Nullable<System.Guid> objectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComponent_ProjectGUID_ByObjectGUID", projectGUIDParameter, objectGUIDParameter);
        }
    
        public virtual int UpdateComponent_SKU_ByObjectGUID(string sKU, Nullable<System.Guid> objectGUID)
        {
            var sKUParameter = sKU != null ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(string));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComponent_SKU_ByObjectGUID", sKUParameter, objectGUIDParameter);
        }
    
        public virtual int UpdateComponent_Supplier_ByObjectGUID(string supplier, Nullable<System.Guid> objectGUID)
        {
            var supplierParameter = supplier != null ?
                new ObjectParameter("Supplier", supplier) :
                new ObjectParameter("Supplier", typeof(string));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComponent_Supplier_ByObjectGUID", supplierParameter, objectGUIDParameter);
        }
    
        public virtual int UpdateProject_Comments_ByProjectGUID(string comments, Nullable<System.Guid> projectGUID)
        {
            var commentsParameter = comments != null ?
                new ObjectParameter("Comments", comments) :
                new ObjectParameter("Comments", typeof(string));
    
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProject_Comments_ByProjectGUID", commentsParameter, projectGUIDParameter);
        }
    
        public virtual int UpdateProject_Description_ByProjectGUID(string description, Nullable<System.Guid> projectGUID)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProject_Description_ByProjectGUID", descriptionParameter, projectGUIDParameter);
        }
    
        public virtual int UpdateProject_Shares_ByProjectGUID(Nullable<double> shares, Nullable<System.Guid> projectGUID)
        {
            var sharesParameter = shares.HasValue ?
                new ObjectParameter("Shares", shares) :
                new ObjectParameter("Shares", typeof(double));
    
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProject_Shares_ByProjectGUID", sharesParameter, projectGUIDParameter);
        }
    
        public virtual int UpdateRole_Description_ByName(string description, string name)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateRole_Description_ByName", descriptionParameter, nameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Component_GetRights(Nullable<System.Guid> componentGUID, Nullable<System.Guid> userGUID)
        {
            var componentGUIDParameter = componentGUID.HasValue ?
                new ObjectParameter("ComponentGUID", componentGUID) :
                new ObjectParameter("ComponentGUID", typeof(System.Guid));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Component_GetRights", componentGUIDParameter, userGUIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Project_GetRights(Nullable<System.Guid> projectGUID, Nullable<System.Guid> userGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Project_GetRights", projectGUIDParameter, userGUIDParameter);
        }
    
        public virtual ObjectResult<GetProject_Result> GetProject(Nullable<System.Guid> gUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProject_Result>("GetProject", gUIDParameter);
        }
    
        public virtual ObjectResult<GetUsers_ByProjectGUID_Result> GetUsers_ByProjectGUID(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsers_ByProjectGUID_Result>("GetUsers_ByProjectGUID", projectGUIDParameter);
        }
    
        public virtual ObjectResult<GetProjects_ByUserGUID_Result> GetProjects_ByUserGUID(Nullable<System.Guid> userGUID)
        {
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjects_ByUserGUID_Result>("GetProjects_ByUserGUID", userGUIDParameter);
        }
    
        public virtual int UpdateProject(Nullable<System.Guid> projectGUID, string projectName, string description)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            var projectNameParameter = projectName != null ?
                new ObjectParameter("ProjectName", projectName) :
                new ObjectParameter("ProjectName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProject", projectGUIDParameter, projectNameParameter, descriptionParameter);
        }
    
        public virtual int DeleteProject(Nullable<System.Guid> projectGUID)
        {
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProject", projectGUIDParameter);
        }
    
        public virtual int CreateToken(Nullable<System.Guid> gUID, Nullable<System.Guid> creatorGUID, Nullable<System.DateTime> expires)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var creatorGUIDParameter = creatorGUID.HasValue ?
                new ObjectParameter("CreatorGUID", creatorGUID) :
                new ObjectParameter("CreatorGUID", typeof(System.Guid));
    
            var expiresParameter = expires.HasValue ?
                new ObjectParameter("Expires", expires) :
                new ObjectParameter("Expires", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateToken", gUIDParameter, creatorGUIDParameter, expiresParameter);
        }
    
        public virtual int DeleteToken(Nullable<System.Guid> gUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteToken", gUIDParameter);
        }
    
        public virtual int ConfirmEmailAddress(Nullable<System.Guid> gUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfirmEmailAddress", gUIDParameter);
        }
    
        public virtual ObjectResult<GetColleagues_ByUserGUID_Result> GetColleagues_ByUserGUID(Nullable<System.Guid> gUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetColleagues_ByUserGUID_Result>("GetColleagues_ByUserGUID", gUIDParameter);
        }
    
        public virtual ObjectResult<GetUser_ByGUID_Result> GetUser_ByGUID(Nullable<System.Guid> gUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUser_ByGUID_Result>("GetUser_ByGUID", gUIDParameter);
        }
    
        public virtual int User_ChangePassword(Nullable<System.Guid> gUID, string pwd)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("Pwd", pwd) :
                new ObjectParameter("Pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("User_ChangePassword", gUIDParameter, pwdParameter);
        }
    
        public virtual ObjectResult<GetComponents__ByObjectGUID_Result> GetComponents_ByObjectGUID(Nullable<System.Guid> objectGUID)
        {
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetComponents__ByObjectGUID_Result>("GetComponents_ByObjectGUID", objectGUIDParameter);
        }
    
        public virtual int AddColleague(Nullable<System.Guid> gUID, Nullable<System.Guid> colleagueGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddColleague", gUIDParameter, colleagueGUIDParameter);
        }
    
        public virtual int DeleteColleague(Nullable<System.Guid> gUID, Nullable<System.Guid> colleagueGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteColleague", gUIDParameter, colleagueGUIDParameter);
        }
    
        public virtual int User_AddColleague(Nullable<System.Guid> gUID, Nullable<System.Guid> colleagueGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("User_AddColleague", gUIDParameter, colleagueGUIDParameter);
        }
    
        public virtual int User_DeleteColleague(Nullable<System.Guid> gUID, Nullable<System.Guid> colleagueGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("User_DeleteColleague", gUIDParameter, colleagueGUIDParameter);
        }
    
        public virtual int UpdateColleague(Nullable<System.Guid> gUID, Nullable<System.Guid> colleagueGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var colleagueGUIDParameter = colleagueGUID.HasValue ?
                new ObjectParameter("ColleagueGUID", colleagueGUID) :
                new ObjectParameter("ColleagueGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateColleague", gUIDParameter, colleagueGUIDParameter);
        }
    
        public virtual int UpdateStakeholders(Nullable<System.Guid> gUID, Nullable<double> shares, Nullable<System.Guid> projectGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var sharesParameter = shares.HasValue ?
                new ObjectParameter("Shares", shares) :
                new ObjectParameter("Shares", typeof(double));
    
            var projectGUIDParameter = projectGUID.HasValue ?
                new ObjectParameter("ProjectGUID", projectGUID) :
                new ObjectParameter("ProjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStakeholders", gUIDParameter, sharesParameter, projectGUIDParameter);
        }
    
        public virtual ObjectResult<FindQPoint_ByPropertyValue_Result> FindQPoint_ByPropertyValue(string property, string propertyValue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("Property", property) :
                new ObjectParameter("Property", typeof(string));
    
            var propertyValueParameter = propertyValue != null ?
                new ObjectParameter("PropertyValue", propertyValue) :
                new ObjectParameter("PropertyValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FindQPoint_ByPropertyValue_Result>("FindQPoint_ByPropertyValue", propertyParameter, propertyValueParameter);
        }
    
        public virtual int DeleteComponent_ByObjectGUID(Nullable<System.Guid> objectGUID)
        {
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteComponent_ByObjectGUID", objectGUIDParameter);
        }
    
        public virtual ObjectResult<GetStakeholder_ByGUID_Result> GetStakeholder_ByGUID(Nullable<System.Guid> gUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStakeholder_ByGUID_Result>("GetStakeholder_ByGUID", gUIDParameter);
        }
    
        public virtual int AddNewQuery(Nullable<System.Guid> qpointGUID, Nullable<System.Guid> sourceGUID, string query)
        {
            var qpointGUIDParameter = qpointGUID.HasValue ?
                new ObjectParameter("QpointGUID", qpointGUID) :
                new ObjectParameter("QpointGUID", typeof(System.Guid));
    
            var sourceGUIDParameter = sourceGUID.HasValue ?
                new ObjectParameter("SourceGUID", sourceGUID) :
                new ObjectParameter("SourceGUID", typeof(System.Guid));
    
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddNewQuery", qpointGUIDParameter, sourceGUIDParameter, queryParameter);
        }
    
        public virtual int CreateComponentFromQpoints(Nullable<System.Guid> gUID, Nullable<System.Guid> qPointGUID, Nullable<System.Guid> parentGUID, Nullable<int> amountInParent)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var qPointGUIDParameter = qPointGUID.HasValue ?
                new ObjectParameter("QPointGUID", qPointGUID) :
                new ObjectParameter("QPointGUID", typeof(System.Guid));
    
            var parentGUIDParameter = parentGUID.HasValue ?
                new ObjectParameter("ParentGUID", parentGUID) :
                new ObjectParameter("ParentGUID", typeof(System.Guid));
    
            var amountInParentParameter = amountInParent.HasValue ?
                new ObjectParameter("AmountInParent", amountInParent) :
                new ObjectParameter("AmountInParent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateComponentFromQpoints", gUIDParameter, qPointGUIDParameter, parentGUIDParameter, amountInParentParameter);
        }
    
        public virtual int CreateNewQpoints(Nullable<System.Guid> qpointGUID, string name, string description)
        {
            var qpointGUIDParameter = qpointGUID.HasValue ?
                new ObjectParameter("QpointGUID", qpointGUID) :
                new ObjectParameter("QpointGUID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateNewQpoints", qpointGUIDParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int CreateQpoints(string name, string description, Nullable<System.Guid> gUID)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateQpoints", nameParameter, descriptionParameter, gUIDParameter);
        }
    
        public virtual int DeleteQpoint_ByQpointGUID(Nullable<System.Guid> qpointGUID)
        {
            var qpointGUIDParameter = qpointGUID.HasValue ?
                new ObjectParameter("QpointGUID", qpointGUID) :
                new ObjectParameter("QpointGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteQpoint_ByQpointGUID", qpointGUIDParameter);
        }
    
        public virtual int DeleteQuery_ByQpointGUID(Nullable<System.Guid> qpointGUID)
        {
            var qpointGUIDParameter = qpointGUID.HasValue ?
                new ObjectParameter("QpointGUID", qpointGUID) :
                new ObjectParameter("QpointGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteQuery_ByQpointGUID", qpointGUIDParameter);
        }
    
        public virtual ObjectResult<GetCategories_Result> GetCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategories_Result>("GetCategories");
        }
    
        public virtual ObjectResult<GetQPoint_BySourceName_Result> GetQPoint_BySourceName(Nullable<System.Guid> objectGUID, string sourceName)
        {
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            var sourceNameParameter = sourceName != null ?
                new ObjectParameter("SourceName", sourceName) :
                new ObjectParameter("SourceName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQPoint_BySourceName_Result>("GetQPoint_BySourceName", objectGUIDParameter, sourceNameParameter);
        }
    
        public virtual ObjectResult<GetSourceProduct_ByObjectGUID_Result> GetSourceProduct_ByObjectGUID(Nullable<System.Guid> parentGUID, Nullable<System.Guid> objectGUID)
        {
            var parentGUIDParameter = parentGUID.HasValue ?
                new ObjectParameter("ParentGUID", parentGUID) :
                new ObjectParameter("ParentGUID", typeof(System.Guid));
    
            var objectGUIDParameter = objectGUID.HasValue ?
                new ObjectParameter("ObjectGUID", objectGUID) :
                new ObjectParameter("ObjectGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSourceProduct_ByObjectGUID_Result>("GetSourceProduct_ByObjectGUID", parentGUIDParameter, objectGUIDParameter);
        }
    
        public virtual int UpdateQpoint_ByQpointGUID(Nullable<System.Guid> qpointGUID, string name, string description)
        {
            var qpointGUIDParameter = qpointGUID.HasValue ?
                new ObjectParameter("QpointGUID", qpointGUID) :
                new ObjectParameter("QpointGUID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateQpoint_ByQpointGUID", qpointGUIDParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int UpdateQuery_ByQpointGUID(Nullable<System.Guid> qpointGUID, Nullable<System.Guid> sourceGUID, string query)
        {
            var qpointGUIDParameter = qpointGUID.HasValue ?
                new ObjectParameter("QpointGUID", qpointGUID) :
                new ObjectParameter("QpointGUID", typeof(System.Guid));
    
            var sourceGUIDParameter = sourceGUID.HasValue ?
                new ObjectParameter("SourceGUID", sourceGUID) :
                new ObjectParameter("SourceGUID", typeof(System.Guid));
    
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateQuery_ByQpointGUID", qpointGUIDParameter, sourceGUIDParameter, queryParameter);
        }
    
        public virtual int CreateNewLabel(string label, Nullable<System.Guid> categoryGUID, Nullable<System.Guid> qpointGUID)
        {
            var labelParameter = label != null ?
                new ObjectParameter("Label", label) :
                new ObjectParameter("Label", typeof(string));
    
            var categoryGUIDParameter = categoryGUID.HasValue ?
                new ObjectParameter("CategoryGUID", categoryGUID) :
                new ObjectParameter("CategoryGUID", typeof(System.Guid));
    
            var qpointGUIDParameter = qpointGUID.HasValue ?
                new ObjectParameter("QpointGUID", qpointGUID) :
                new ObjectParameter("QpointGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateNewLabel", labelParameter, categoryGUIDParameter, qpointGUIDParameter);
        }
    
        public virtual int DeleteLabel_ByCategoryGUID(Nullable<System.Guid> categoryGUID)
        {
            var categoryGUIDParameter = categoryGUID.HasValue ?
                new ObjectParameter("CategoryGUID", categoryGUID) :
                new ObjectParameter("CategoryGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLabel_ByCategoryGUID", categoryGUIDParameter);
        }
    
        public virtual ObjectResult<string> GetAllLabels(Nullable<System.Guid> gUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAllLabels", gUIDParameter);
        }
    
        public virtual ObjectResult<GetLabels_ByCategoryGUID_Result> GetLabels_ByCategoryGUID(Nullable<System.Guid> gUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLabels_ByCategoryGUID_Result>("GetLabels_ByCategoryGUID", gUIDParameter);
        }
    }
}
