//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIn.Ventures.BaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public string Type { get; set; }
        public string Text { get; set; }
        public string TypeID { get; set; }
    
        public virtual AlertType AlertType { get; set; }
    }
}
