//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIn.Ventures.BaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archived_RoleToProject
    {
        public System.Guid UserGUID { get; set; }
        public System.Guid ProjectGUID { get; set; }
        public int Role { get; set; }
    
        public virtual Archived_Project Archived_Project { get; set; }
    }
}
