//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIn.Ventures.BaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class QPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QPoint()
        {
            this.QPointToCategories = new HashSet<QPointToCategory>();
            this.QPointToProperties = new HashSet<QPointToProperty>();
            this.QPointToSources = new HashSet<QPointToSource>();
        }
    
        public System.Guid GUID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> DataClassGUID { get; set; }
        public string Description { get; set; }
    
        public virtual DataClass DataClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QPointToCategory> QPointToCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QPointToProperty> QPointToProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QPointToSource> QPointToSources { get; set; }
    }
}
