//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace MIX.Data.WebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UpdaterSoap", Namespace="http://tempuri.org/")]
    public partial class Updater : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateAttributeOperationCompleted;
        
        /// <remarks/>
        public Updater() {
            this.Url = "http://damartwebp1.ct.pb.com:304/MIXPush-DEV/Updater.asmx";
        }
        
        /// <remarks/>
        public event UpdateAttributeCompletedEventHandler UpdateAttributeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAttribute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateAttribute(string DataSource, string ObjectClass, string DataClass, string Attribute, string Obj, string Instance, string Value, System.DateTime Updated) {
            this.Invoke("UpdateAttribute", new object[] {
                        DataSource,
                        ObjectClass,
                        DataClass,
                        Attribute,
                        Obj,
                        Instance,
                        Value,
                        Updated});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateAttribute(string DataSource, string ObjectClass, string DataClass, string Attribute, string Obj, string Instance, string Value, System.DateTime Updated, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateAttribute", new object[] {
                        DataSource,
                        ObjectClass,
                        DataClass,
                        Attribute,
                        Obj,
                        Instance,
                        Value,
                        Updated}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateAttribute(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void UpdateAttributeAsync(string DataSource, string ObjectClass, string DataClass, string Attribute, string Obj, string Instance, string Value, System.DateTime Updated) {
            this.UpdateAttributeAsync(DataSource, ObjectClass, DataClass, Attribute, Obj, Instance, Value, Updated, null);
        }
        
        /// <remarks/>
        public void UpdateAttributeAsync(string DataSource, string ObjectClass, string DataClass, string Attribute, string Obj, string Instance, string Value, System.DateTime Updated, object userState) {
            if ((this.UpdateAttributeOperationCompleted == null)) {
                this.UpdateAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAttributeOperationCompleted);
            }
            this.InvokeAsync("UpdateAttribute", new object[] {
                        DataSource,
                        ObjectClass,
                        DataClass,
                        Attribute,
                        Obj,
                        Instance,
                        Value,
                        Updated}, this.UpdateAttributeOperationCompleted, userState);
        }
        
        private void OnUpdateAttributeOperationCompleted(object arg) {
            if ((this.UpdateAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAttributeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void UpdateAttributeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}
