//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIn.Ventures.BaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archived_Stakeholder
    {
        public System.Guid GUID { get; set; }
        public Nullable<double> Shares { get; set; }
        public Nullable<System.Guid> ProjectGUID { get; set; }
        public bool IsUser { get; set; }
    
        public virtual Archived_Project Archived_Project { get; set; }
    }
}
