//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIn.Ventures.BaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colleague
    {
        public System.Guid UserGUID { get; set; }
        public System.Guid ColleagueGUID { get; set; }
        public double Weight { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
