//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIn.Ventures.BaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentToComponent
    {
        public System.Guid ParentGUID { get; set; }
        public System.Guid ObjectGUID { get; set; }
        public int amount { get; set; }
        public Nullable<System.Guid> ProjectGUID { get; set; }
        public Nullable<System.Guid> SourceGUID { get; set; }
        public string ItemKey { get; set; }
        public Nullable<System.DateTime> ItemDate { get; set; }
    
        public virtual Component Component { get; set; }
    }
}
