//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace MIX2.Acquisition.IBM.Tivoli.EndpointService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RelevanceBinding", Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class RelevanceBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRelevanceResultOperationCompleted;
        
        private RequestHeader requestHeaderElementField;
        
        private ResponseHeader responseHeaderElementField;
        
        private System.Threading.SendOrPostCallback GetStructuredRelevanceResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RelevanceBinding() {
            this.Url = global::MIX2.Acquisition.IBM.Properties.Settings.Default.MIX2_Acquisition_IBM_Tivoli_EndpointService_WebReportsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestHeader RequestHeaderElement {
            get {
                return this.requestHeaderElementField;
            }
            set {
                this.requestHeaderElementField = value;
            }
        }
        
        public ResponseHeader ResponseHeaderElement {
            get {
                return this.responseHeaderElementField;
            }
            set {
                this.responseHeaderElementField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRelevanceResultCompletedEventHandler GetRelevanceResultCompleted;
        
        /// <remarks/>
        public event GetStructuredRelevanceResultCompletedEventHandler GetStructuredRelevanceResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bigfix.com/Relevance/soapaction", RequestNamespace="http://schemas.bigfix.com/Relevance", ResponseNamespace="http://schemas.bigfix.com/Relevance", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("a")]
        public string[] GetRelevanceResult(string relevanceExpr, string username, string password) {
            object[] results = this.Invoke("GetRelevanceResult", new object[] {
                        relevanceExpr,
                        username,
                        password});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRelevanceResultAsync(string relevanceExpr, string username, string password) {
            this.GetRelevanceResultAsync(relevanceExpr, username, password, null);
        }
        
        /// <remarks/>
        public void GetRelevanceResultAsync(string relevanceExpr, string username, string password, object userState) {
            if ((this.GetRelevanceResultOperationCompleted == null)) {
                this.GetRelevanceResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRelevanceResultOperationCompleted);
            }
            this.InvokeAsync("GetRelevanceResult", new object[] {
                        relevanceExpr,
                        username,
                        password}, this.GetRelevanceResultOperationCompleted, userState);
        }
        
        private void OnGetRelevanceResultOperationCompleted(object arg) {
            if ((this.GetRelevanceResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRelevanceResultCompleted(this, new GetRelevanceResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderElement")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderElement", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bigfix.com/Relevance/soapaction", RequestNamespace="http://schemas.bigfix.com/Relevance", ResponseNamespace="http://schemas.bigfix.com/Relevance", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("StructuredRelevanceResult")]
        public StructuredRelevanceResult GetStructuredRelevanceResult(string relevanceExpr) {
            object[] results = this.Invoke("GetStructuredRelevanceResult", new object[] {
                        relevanceExpr});
            return ((StructuredRelevanceResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetStructuredRelevanceResultAsync(string relevanceExpr) {
            this.GetStructuredRelevanceResultAsync(relevanceExpr, null);
        }
        
        /// <remarks/>
        public void GetStructuredRelevanceResultAsync(string relevanceExpr, object userState) {
            if ((this.GetStructuredRelevanceResultOperationCompleted == null)) {
                this.GetStructuredRelevanceResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStructuredRelevanceResultOperationCompleted);
            }
            this.InvokeAsync("GetStructuredRelevanceResult", new object[] {
                        relevanceExpr}, this.GetStructuredRelevanceResultOperationCompleted, userState);
        }
        
        private void OnGetStructuredRelevanceResultOperationCompleted(object arg) {
            if ((this.GetStructuredRelevanceResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStructuredRelevanceResultCompleted(this, new GetStructuredRelevanceResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserManagementBinding", Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class UserManagementBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private RequestHeader requestHeaderElementField;
        
        private ResponseHeader responseHeaderElementField;
        
        private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserManagementBinding() {
            this.Url = global::MIX2.Acquisition.IBM.Properties.Settings.Default.MIX2_Acquisition_IBM_Tivoli_EndpointService_WebReportsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestHeader RequestHeaderElement {
            get {
                return this.requestHeaderElementField;
            }
            set {
                this.requestHeaderElementField = value;
            }
        }
        
        public ResponseHeader ResponseHeaderElement {
            get {
                return this.responseHeaderElementField;
            }
            set {
                this.responseHeaderElementField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateUserCompletedEventHandler CreateUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderElement")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderElement", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bigfix.com/Relevance/soapaction", RequestNamespace="http://schemas.bigfix.com/Relevance", ResponseNamespace="http://schemas.bigfix.com/Relevance", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("success")]
        public bool CreateUser(UserAccount user) {
            object[] results = this.Invoke("CreateUser", new object[] {
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUserAsync(UserAccount user) {
            this.CreateUserAsync(user, null);
        }
        
        /// <remarks/>
        public void CreateUserAsync(UserAccount user, object userState) {
            if ((this.CreateUserOperationCompleted == null)) {
                this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
            }
            this.InvokeAsync("CreateUser", new object[] {
                        user}, this.CreateUserOperationCompleted, userState);
        }
        
        private void OnCreateUserOperationCompleted(object arg) {
            if ((this.CreateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DashboardVariableBinding", Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class DashboardVariableBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private RequestHeader requestHeaderElementField;
        
        private ResponseHeader responseHeaderElementField;
        
        private System.Threading.SendOrPostCallback DeleteSharedVariableOperationCompleted;
        
        private System.Threading.SendOrPostCallback StoreSharedVariableOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DashboardVariableBinding() {
            this.Url = global::MIX2.Acquisition.IBM.Properties.Settings.Default.MIX2_Acquisition_IBM_Tivoli_EndpointService_WebReportsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestHeader RequestHeaderElement {
            get {
                return this.requestHeaderElementField;
            }
            set {
                this.requestHeaderElementField = value;
            }
        }
        
        public ResponseHeader ResponseHeaderElement {
            get {
                return this.responseHeaderElementField;
            }
            set {
                this.responseHeaderElementField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteSharedVariableCompletedEventHandler DeleteSharedVariableCompleted;
        
        /// <remarks/>
        public event StoreSharedVariableCompletedEventHandler StoreSharedVariableCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderElement")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderElement", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bigfix.com/Relevance/soapaction", RequestNamespace="http://schemas.bigfix.com/Relevance", ResponseNamespace="http://schemas.bigfix.com/Relevance", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("success")]
        public bool DeleteSharedVariable(DashboardVariableIdentifier dashboardVariableIdentifier) {
            object[] results = this.Invoke("DeleteSharedVariable", new object[] {
                        dashboardVariableIdentifier});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteSharedVariableAsync(DashboardVariableIdentifier dashboardVariableIdentifier) {
            this.DeleteSharedVariableAsync(dashboardVariableIdentifier, null);
        }
        
        /// <remarks/>
        public void DeleteSharedVariableAsync(DashboardVariableIdentifier dashboardVariableIdentifier, object userState) {
            if ((this.DeleteSharedVariableOperationCompleted == null)) {
                this.DeleteSharedVariableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSharedVariableOperationCompleted);
            }
            this.InvokeAsync("DeleteSharedVariable", new object[] {
                        dashboardVariableIdentifier}, this.DeleteSharedVariableOperationCompleted, userState);
        }
        
        private void OnDeleteSharedVariableOperationCompleted(object arg) {
            if ((this.DeleteSharedVariableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSharedVariableCompleted(this, new DeleteSharedVariableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeaderElement")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeaderElement", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bigfix.com/Relevance/soapaction", RequestNamespace="http://schemas.bigfix.com/Relevance", ResponseNamespace="http://schemas.bigfix.com/Relevance", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("success")]
        public bool StoreSharedVariable(DashboardVariableIdentifier dashboardVariableIdentifier, string variableValue) {
            object[] results = this.Invoke("StoreSharedVariable", new object[] {
                        dashboardVariableIdentifier,
                        variableValue});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void StoreSharedVariableAsync(DashboardVariableIdentifier dashboardVariableIdentifier, string variableValue) {
            this.StoreSharedVariableAsync(dashboardVariableIdentifier, variableValue, null);
        }
        
        /// <remarks/>
        public void StoreSharedVariableAsync(DashboardVariableIdentifier dashboardVariableIdentifier, string variableValue, object userState) {
            if ((this.StoreSharedVariableOperationCompleted == null)) {
                this.StoreSharedVariableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStoreSharedVariableOperationCompleted);
            }
            this.InvokeAsync("StoreSharedVariable", new object[] {
                        dashboardVariableIdentifier,
                        variableValue}, this.StoreSharedVariableOperationCompleted, userState);
        }
        
        private void OnStoreSharedVariableOperationCompleted(object arg) {
            if ((this.StoreSharedVariableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StoreSharedVariableCompleted(this, new StoreSharedVariableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticateHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    [System.Xml.Serialization.XmlRootAttribute("RequestHeaderElement", Namespace="http://schemas.bigfix.com/Relevance", IsNullable=false)]
    public partial class RequestHeader : System.Web.Services.Protocols.SoapHeader {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class DashboardVariableIdentifier {
        
        private string dashboardIDField;
        
        private string variableNameField;
        
        private long databaseIDField;
        
        private bool databaseIDFieldSpecified;
        
        /// <remarks/>
        public string dashboardID {
            get {
                return this.dashboardIDField;
            }
            set {
                this.dashboardIDField = value;
            }
        }
        
        /// <remarks/>
        public string variableName {
            get {
                return this.variableNameField;
            }
            set {
                this.variableNameField = value;
            }
        }
        
        /// <remarks/>
        public long databaseID {
            get {
                return this.databaseIDField;
            }
            set {
                this.databaseIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool databaseIDSpecified {
            get {
                return this.databaseIDFieldSpecified;
            }
            set {
                this.databaseIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class UserAccount {
        
        private string logonNameField;
        
        private string fullNameField;
        
        private string passwordField;
        
        private string roleField;
        
        /// <remarks/>
        public string logonName {
            get {
                return this.logonNameField;
            }
            set {
                this.logonNameField = value;
            }
        }
        
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class ResultList {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("FloatingPoint", typeof(double))]
        [System.Xml.Serialization.XmlElementAttribute("Integer", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("String", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Tuple", typeof(ResultList))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        FloatingPoint,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Tuple,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class StructuredRelevanceResult {
        
        private ResultList resultsField;
        
        private bool pluralField;
        
        private bool pluralFieldSpecified;
        
        private string typeField;
        
        private string evaltimeField;
        
        private string errorField;
        
        /// <remarks/>
        public ResultList results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public bool plural {
            get {
                return this.pluralField;
            }
            set {
                this.pluralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pluralSpecified {
            get {
                return this.pluralFieldSpecified;
            }
            set {
                this.pluralFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string evaltime {
            get {
                return this.evaltimeField;
            }
            set {
                this.evaltimeField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class LoginHeader : RequestHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    public partial class AuthenticateHeader : RequestHeader {
        
        private string usernameField;
        
        private string sessionTokenField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string sessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bigfix.com/Relevance")]
    [System.Xml.Serialization.XmlRootAttribute("ResponseHeaderElement", Namespace="http://schemas.bigfix.com/Relevance", IsNullable=false)]
    public partial class ResponseHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string sessionTokenField;
        
        /// <remarks/>
        public string sessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRelevanceResultCompletedEventHandler(object sender, GetRelevanceResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRelevanceResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRelevanceResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStructuredRelevanceResultCompletedEventHandler(object sender, GetStructuredRelevanceResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStructuredRelevanceResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStructuredRelevanceResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StructuredRelevanceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StructuredRelevanceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateUserCompletedEventHandler(object sender, CreateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteSharedVariableCompletedEventHandler(object sender, DeleteSharedVariableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteSharedVariableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteSharedVariableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StoreSharedVariableCompletedEventHandler(object sender, StoreSharedVariableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StoreSharedVariableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StoreSharedVariableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591